# Generated by Django 2.2.11 on 2020-04-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='id_admin',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historial_usuarios',
            name='id_historial_us',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plazas',
            name='codigo_plaza',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='cod_tarifa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_ticket',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tipo_vehiculo',
            name='codigo_tipo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_usuario',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='id_vehiculo',
            field=models.CharField(max_length=20),
        ),
    ]
