# Generated by Django 2.2.11 on 2020-04-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0002_auto_20200402_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ticket', models.CharField(max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('valor_pagar', models.CharField(max_length=20)),
                ('vehiculo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vehiculo', models.CharField(max_length=20)),
                ('id_placa_vehiculo', models.CharField(max_length=20)),
                ('id_propietario', models.CharField(max_length=20)),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(null=True)),
                ('tipo_vehiculo', models.CharField(max_length=20)),
                ('plaza_usada', models.CharField(max_length=20)),
            ],
        ),
    ]
