# Generated by Django 2.2.11 on 2020-04-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0003_ticket1_vehiculo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo1',
            name='id_vehiculo',
        ),
    ]
