# Generated by Django 2.2.11 on 2020-04-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0004_remove_vehiculo1_id_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket1',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo1',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
