# Generated by Django 2.2.11 on 2020-04-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0005_auto_20200415_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo1',
            name='facturada',
            field=models.BooleanField(default=False),
        ),
    ]
