# Generated by Django 2.2.11 on 2020-04-21 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0006_vehiculo1_facturada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket1',
            name='id_ticket',
        ),
    ]
